# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c


sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test -v test_env.py'
        - PYTHON_VERSION=3.5
        - NUMPY_VERSION=1.9
        - SCIPY_VERSION=0.14


matrix:
    include:

        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=stable CONDA_DEPENDENCIES='scipy libgfortran'

before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - eval $TEST_CMD
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
