# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
        - PYTHON_VERSION=3.5
        - CONDA=True

matrix:
    include:
        - os: osx
          env: CONDA=False ARCH=i386 PIP_DEPENDENCIES="numpy scipy astropy"

before_install:
    - ln -s . ci-helpers
    - if [[ $CONDA == True ]]; then
        source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh;
      else
        source "ci-helpers/travis/setup_python_"$ARCH".sh";
      fi

script:
   - eval $TEST_CMD
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
