# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux
    - osx

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
        - PYTHON_VERSION=3.5

    matrix:
        - SETUP_CMD='egg_info'
          TEST_CMD='python --version'

        - SETUP_CMD='test'

        # Starting with the dev versions as they take the longest to run
        - SETUP_CMD='test' NUMPY_VERSION=1.10 ASTROPY_VERSION=dev

        # For the Numpy dev build, we also specify a conda package that depends
        # on Numpy to make sure that Numpy dev is used (because conda will also
        # install Numpy stable)

        - SETUP_CMD='test' NUMPY_VERSION=dev
               CONDA_DEPENDENCIES='scipy'

        - SETUP_CMD='build_sphinx'

        - SETUP_CMD='build_docs' PYTHON_VERSION=2.7

        - MAIN_CMD='pep8'
               TEST_CMD='pep8 --version'

        - SETUP_CMD='test' NUMPY_VERSION=1.10

        - SETUP_CMD='test' ASTROPY_VERSION=stable

        - SETUP_CMD='test' NUMPY_VERSION=1.9 CONDA_DEPENDENCIES='requests'

        - SETUP_CMD='test' NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0
               CONDA_DEPENDENCIES='matplotlib h5py'
               PIP_DEPENDENCIES='astrodendro'

        - SETUP_CMD='test' NUMPY_VERSION=stable

        - SETUP_CMD='test' ASTROPY_VERSION=LTS

        - SETUP_CMD='test --parallel'
               TEST_CMD='py.test -n 4 test_env.py'

        - SETUP_CMD='test --open-files'

        - SETUP_CMD='test --coverage'
               TEST_CMD='coverage run test_env.py'
               NUMPY_VERSION=1.10 ASTROPY_VERSION=lts

        - SETUP_CMD='test' PYTHON_VERSION=2.7
               CONDA_CHANNELS='astropy-ci-extras astrofrog'
               CONDA_DEPENDENCIES='PyQt5'

        - SETUP_CMD='test' DEBUG=True

        - SETUP_CMD='test' DEBUG=False


before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - eval $TEST_CMD
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
